#!/usr/bin/env bash
# InFocus launcher script.

INFOCUS_PATH="/usr/lib/infocus"

cd $INFOCUS_PATH

PHP_FOUND=$(command -v php)

if [ "$PHP_FOUND" = "" ]; then
    echo "Please install php (http://php.net/)"
    exit
fi

runui()
{
    local port=8080

    if [ "$1" != "" ]; then
        if [ "$1" != "ui" ]; then
            port=$1
        fi
    fi

    until php -d extension=pdo_sqlite.so -d open_basedir="" -S localhost:$port  & 2> /dev/null; do
        port=$(($port+1))
    done

    local server=$!
    local browser=""

    local chromium_installed=$(command -v chromium)
    local firefox_installed=$(command -v firefox)

    if [ -n "$chromium_installed" ]; then
        chromium --app="http://localhost:$port" &
        browser="chromium"
    elif [ -n "$firefox_installed" ]; then
        firefox "http://localhost:$port" &
        browser="firefox"
    fi

    sleep 7 # wait to properly get browser process id

    local id=$(pgrep -n -f $browser)

    while [ "$(ps -A | grep $id)" != "" ]; do
        sleep 1
    done

    echo -n "Shutting webserver down... "
    kill $server
    echo "(Done!)"
}

case $1 in
    'ui' )
        shift 2
        runui $1
        exit
        ;;
    'log' )
        php -d extension=pdo_sqlite.so \
            -d open_basedir="" \
            $INFOCUS_PATH/main.php log
        exit
        ;;
esac

php -d extension=pdo_sqlite.so \
    -d open_basedir="" \
    $INFOCUS_PATH/main.php $@
